<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "scientist".
 *
 * @property integer $id
 * @property string $name
 * @property string $city
 * @property string $biography
 * @property string $achievements
 */
class Scientist extends \yii\db\ActiveRecord
{
    /**
     * Статус ученого: активен.
     */
    const STATUS_ACTIVE = 1;
    /**
     * Статус ученого: удален.
     */
    const STATUS_DELETE = 0;

    public $file;
    public $del_img;
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'scientist';
    }

    public function getStatuses()
    {
        return [
            Scientist::STATUS_ACTIVE => 'Активен',
            Scientist::STATUS_DELETE => 'Удален',
        ];
    }

    public function getStatusName()
    {
        return ArrayHelper::getValue(self::getStatusesArray(), $this->status);
    }
 
    public static function getStatusesArray()
    {
        return [
            self::STATUS_DELETE => 'Удален',
            self::STATUS_ACTIVE => 'Активен',
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'city', 'biography'], 'required'],
            [['biography'], 'string'],
            [['name', 'city'], 'string', 'max' => 100],
            [['achievements'], 'string', 'max' => 100],
            [['file'], 'file', 'extensions' => 'png, jpg'],
            [['del_img'], 'boolean'],

        ];
    }

    /**
     *
     */
    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
        
        if (empty($this->image) OR !file_exists(Yii::getAlias('@app/public_html'.$this->image))) {
            $this->image = '/images/teacher.jpg';
        }

        Yii::info('its event after find file exist '.$this->image, __METHOD__);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Имя',
            'city' => 'City',
            'biography' => 'Biography',
            'achievements' => 'Achievements',
            'status' => 'Статус',
        ];
    }

    //public function getScientist($id)
    //{
    //    if (
    //        ($model = Post::findOne($id)) !== null &&
    //        $model->isPublished()
    //    ) {
    //        return $model;
    //    } else {
    //        throw new NotFoundHttpException('The requested post does not exist.');
    //    }
    //}
//
    //protected function isPublished()
    //{
    //    return $this->publish_status === self::STATUS_PUBLISH;
    //}
}
